### ISSUE TITLE
The entries in the 'List' tab of the 'Alphabet' panel are not monospace

### ISSUE THREAD

**Issue by safazi** [nealey/vail#10]
Dichotomous key tab looks great, the list tab should follow the same style.

**Comment by nealey** [comment]
I tried this and thought it was ugly. How would you feel about making the dichotomous key proportional spaced?

**Comment by safazi** [comment]
Not ideal in my opinion, I think monospace has the best readability. Consider capitalizing the letters in both tabs, too.

**Comment by nealey** [comment]
Ew gross, monospace *and* caps?

Okay, fine, I suppose this will make it look more like everywhere else. I feel better now having complained in a ticket nobody will ever read.

**Comment by nealey** [comment]
Fixed in 94914dc
