### ISSUE TITLE
Freetext repeater entry

### ISSUE THREAD

**Issue by nealey** [nealey/vail#17]
It wasn't obvious to most that you could hack the URL to get the repeater. With the PWA, this option is gone. Let the URL fill the repeater name initially, but allow it to be edited.

**Comment by nealey** [comment]
I'm unlikely to implement this in the near future: the current list of "stock" repeaters is probably about the same size as the current list of users, and I'm okay with only clever people figuring out how to make their own private repeater.

**Comment by safazi** [comment]
Consider adding a feature to show users if there is someone else on the repeater. It doesn't have to be the number of people on, for realism' sake, but an indication that you're not beeping into the void would be nice.
