### ISSUE TITLE
Slider for "dit" show WPM

### ISSUE THREAD

**Issue by nealey** [nealey/vail#30]
People keep asking for this.

WPM is actually "words which are only ever 'PARIS' per minute". It is the duration of 50 dits.

(1 PARIS / 50 dits)  * (1 dit / n milliseconds) * (60000 milliseconds / minute)

**Comment by nealey** [comment]
Added in https://github.com/nealey/vail/commit/4f33d7453c30139df7825b204728fd8511c9a2cf

**Comment by rhughes71446** [comment]
In ham radio, the only term operators ever use is #wpm.  15wpm  20wpm etc.   and on most digital transceivers the screen will show WPM as the keyer speed is adjusted.  

Again…most hams want to see WPM
