### ISSUE TITLE
A and B iambic

### ISSUE THREAD

**Issue by nealey** [nealey/vail#31]
Based on my 10 seconds of testing on vband, in B iambic, if you are holding both keys, and transmitting DAH, then release both keys, it tacks on an extra DIT.

This seems wrong. I need some help unpacking how exactly this works.

**Comment by rhughes71446** [comment]
In Mode A you either get continues dits OR dahs.  So for the letter C you must make a movement for each fit and dah.  Right-left-right-left. 

For iambic B mode (sometimes cold the squeeze key method) by holding both keys together at the same time makes alternating dits and dahs automatic.   Do for example for the letter C , you squeeze the keys at the same time but the dah key is touched a split second before the dit key.  So the entire letter is made with one squeeze.   Releasing the dit last.   DAH-dit-dah-DIT.   The first DAH starts the letter and the last  DIT ends it.  One squeeze.    Letters. C F K L Q R Y are mode B letters.   All others would be same as mode A.  Many hams use these which makes for less hand movement.   It just makes for more relaxed sending.  Also at 25 or 30 WPM the iambic almost becomes necessary.

**Comment by rhughes71446** [comment]
Neal… it doesn’t always tack on an extra did.   
a letter might start with a dah and end with a dah.  Ex… K  dah-dit- dah  u start the squeeze with the dah but after the dit you keep the dah… hold the done linger.  

Opposite would be the R  dit dah dit  squeeze with the dit first.   The dah is inserted while still holding the dit.  

When first learning, you have to set your speed very slow to become coordinated with the movements.

**Comment by rhughes71446** [comment]
START 2:30 into the video and you will get the Perfect Explanation of the B mode.  hams will be pleased to be able to have the choice of A or B.

**Comment by nealey** [comment]
Okay, this sounds simple enough. Thanks for the explanation!

**Comment by rhughes71446** [comment]
Hi Neil. I tried to make a comment on that other page but it didn’t have a place to comment on the Iambic. It seems to work OK for the Iambic B using the bracket keys on a keyboard although it doesn’t feel quite natural, it does work. It doesn’t work using the external paddle.  But really it’s not a big deal the channel numbers are great and the words per minute slider is great.  I appreciate the changes you’ve made.   I don’t understand the general chaos channel. But I have already asked enough favors.  Thanks so much. 

Rich. wb0wls.

**Comment by rhughes71446** [comment]
B doesn’t work with paddle and vband interface. Of course A mode is great.

**Comment by rhughes71446** [comment]
Hi Neale  the iambic B mode does not work at all with my paddle on the
laptop.    Although it does work correctly on my phone using the touch pad.
  Any idea why that would be.  I have tried all the possible combinations
with those 2 little.  Nothing works.  Maybe u can figure it out from the
fact it works on my phone.

**Comment by rhughes71446** [comment]
Hi Neale. As long as you are making changes to it already is a program I am
thoroughly enjoying, would it be possible to add an additional mode it
would be like using a bug. Where are the doors would be just like a
straight Guy and the debts would be repeating as in mode A or B etc. and
would still be adjustable by the slider for the death speed.

Each “dah” created as in a straight key and repeating dits at variable
speeds controled by the dit slider.   Thanks for your consideration of this
additional  mode.  It would give paddle users (which is almost everyone) to
experience bug sending without the purchase of an expensive bug.

Rich. WB0WLS

**Comment by nealey** [comment]
Yeah, Iambic B is horribly, horribly broken. I completely misunderstood what it was. I'll push out a new change to fix it soon.

**Comment by nealey** [comment]
> Hi Neale. As long as you are making changes to it already is a program I am thoroughly enjoying, would it be possible to add an additional mode it would be like using a bug.

That sounds fun, I'll track work on this feature request in #37

**Comment by rhughes71446** [comment]
Any chance of the bug operation.

**Comment by nealey** [comment]
New Iambic A and B implementations are running in testing: https://vail.woozle.org/testing/

I'll wait a little bit to get feedback on this, and if it sounds like I haven't made anything worse, I'll roll it into production this weekend.

**Comment by nealey** [comment]
It's been a heck of a weekend. I've rolled out a timing chart toggle that will hopefully help people explain to me what bugs still remain, and the exact timing of them.

One that I've identified just now is that, in Iambic A or B, when using the VBand adapter (AKA control keys), holding one key down, then tapping the other, the key release on the other triggers both keys to release. The timing diagram actually made this obvious, so it's already helping. Now to figure out why...

**Comment by nealey** [comment]
Oh, you know what, the browser is sending keyup for both keys in that situation. VBand has the same problem for me. So I can't fix this one, it's just an artifact of how the Control key works.

**Comment by nealey** [comment]
I documented this Control on ChromeOS behavior on the wiki.

**Comment by nealey** [comment]
Here is the current state of Iambic input: it works if you have two keys. If you have one key, the switchover on timing is triggering obscure code paths that are an artifact of the frankly kludgy way I slapped Iambic B together. It makes people feel like the timing is off, and it seems to only happen at high speeds.

My plan moving forward is to examine the Iambic B implementations in some other open source projects and copy those. Surely there is some elegant logic here that I'm just not grasping: when I implement that, hopefully, this problem will get cured and the size of the keyer codebase should go down.

**Comment by rhughes71446** [comment]
Neale.  Tnx so much for the mouse flip

**Comment by nealey** [comment]
> Neale. Tnx so much for the mouse flip

housekeeping note: this is in reference to #43

**Comment by nealey** [comment]
http://cq-cq.eu/DJ5IL_rt007.pdf is a fabulous teardown of a whole bunch of different modes. I think I have direction for my B mode keyer from this.

**Comment by nealey** [comment]
Finally, everybody thinks the Iambic A and B implementations feel right.

https://github.com/nealey/vail/commit/9a37907945df4c4b3a9379524e0f378512bc731d
