### ISSUE TITLE
Vail should remember your keying mode

### ISSUE THREAD

**Issue by nealey** [nealey/vail#33]
Since there is now (secret) code to have the vband keys (left and right ctrl) act differently based on which tab has been selected in the keyer section, vail should automatically open that tab when loaded, so people can resume where they left off.

This should just be a matter of stashing another setting away in localStorage.

**Comment by ManOfMeans** [comment]
I do know that VB places a Cookie on the local machine.  This Cookie retains your Callsign and other Settings tab info.  Maybe a similar implementation would suffice.

**Comment by nealey** [comment]
With the overhauled user interface in https://github.com/nealey/vail/commit/f23ea76a4f2a75a5ca296cf86ae822c667197e4d it now remembers keying mode.
