### ISSUE TITLE
Echo on connect

### ISSUE THREAD

**Issue by nealey** [nealey/vail#34]
Sometimes when you connect, you hear your own input when it comes back. Reloading seems to make it go away.

**Comment by ManOfMeans** [comment]
For me, this issue seems to happen about 50% of the time, regardless of the machine I am using to connect with.

**Comment by nealey** [comment]
I've had this happen once or twice, seems like Firefox is more common. Unfortunately, I can't get it to happen when I want to work on it! If anybody finds a way to reliably reproduce this, it'd be spiffarino.

**Comment by nealey** [comment]
Here's the way the echo normally works: whenever you send something out, it has the timestamp where you entered the tone, and the duration of the tone. That pair of values gets added to a "squelch list".

When the repeater sends a request for the exact same pair of numbers as something in the squelch list, it is removed from the squelch list, and not played.

So apparently, somehow, when you load the thing up sometimes, your transmissions aren't getting added to the squelch list. I think it's likely that this is because something is triggering an error before the code runs to append to the list. So if you see this, please open a JavaScript console, and look for any error messages, That would be gold.

**Comment by nealey** [comment]
I finally reproduced this!

```
repeaters.mjs:111 Transmit Array(2)
repeaters.mjs:70 Vail.wsMessage() Array(2)
repeaters.mjs:66 Vail.wsMessage() SQUELCH Array(2)
repeaters.mjs:111 Transmit Array(2)
repeaters.mjs:70 Vail.wsMessage() Array(2)
repeaters.mjs:66 Vail.wsMessage() SQUELCH Array(2)
repeaters.mjs:111 Transmit Array(2)
repeaters.mjs:70 Vail.wsMessage() Array(2)
repeaters.mjs:66 Vail.wsMessage() SQUELCH Array(2)
```

It appears what's happening here is that the client for some reason has two connections open to the repeater. I triggered this by trying to work on #28.

It's possible that the little patch I just added in https://github.com/nealey/vail/commit/d47378ba3714d67d5916a834978a81e3480ddc59 to prevent an intentionally-closed repeater from trying to reconnect may actually have fixed this bug.

Next steps: wait and see if this happens for anyone again. If not, I have to assume that patch fixed things, and I'll close the bug. Let's give it until 2022-06-01.

**Comment by nealey** [comment]
This hasn't happened for an age. That reconnect bug appears to have been the cause.
