### ISSUE TITLE
Add a Dark Mode to the site

### ISSUE THREAD

**Issue by ManOfMeans** [nealey/vail#46]
Could you please add a Dark Mode to the site?  It would help to relieve visual stress when operating at night, and give users better contrast in other situations as well.
Thank you!

**Comment by nealey** [comment]
This depends on your browser actually being able to know you want dark mode. This is available on at least my phone: you just tell the phone to use dark mode. It's a W3C standard doodad so I'm going to pretend like everything will eventually support it.

https://caniuse.com/?search=prefers-color-scheme
