### ISSUE TITLE
Add push notification to browser tab when activity in Repeater

### ISSUE THREAD

**Issue by ManOfMeans** [nealey/vail#49]
A visual indicator in the browser tab would be useful if there is sending activity in the Repeater you're actively in.
An example of this can be seen with Discord.  If a new message appears in a thread, the logo in the browser tab is updated to include a red dot with the number of unread messages.  I propose something similar, but simply a red dot, or a flashing dot that flashes to the pulse of the code being sent.

![image](https://user-images.githubusercontent.com/104023346/168523785-e3d8da04-07c2-4958-bf3e-df0c7c887a99.png)

**Comment by nealey** [comment]
Seems the work I did only applied to the fortunes bot; I'm not getting a color change in general.
